blank_issues_enabled: false
contact_links:
  - name: 🛡️ Security Vulnerability Reporting
    url: https://github.com/switchfiber/switchfiberusers/blob/main/SECURITY.md
    about: Please report potential security vulnerabilities privately according to our security policy.
  - name: 💬 Switch Fiber Customer Care
    url: https://switchfiber.ph/contact
    about: For billing, line installation, and subscriber technical support inquiries.
